images/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^detail/(?P<id>\d+)/$', views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
    url(r'^delete/$', views.image_delete, name='image_delete'),
]

social/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('account.urls')),
    url(r'^', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from sorl.thumbnail import delete as delete_thumbnails, ImageField

class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created')
    title = models.CharField(max_length=240)
    image = ImageField(upload_to='images/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True, db_index=True, blank=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)
    users_view = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_viewed',
                                        blank=True)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id])

    def clear_thumbnails(self):
        delete_thumbnails(self.image)

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments_created')
    image = models.ForeignKey(Image, related_name='comments')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.user.get_full_name, self.image)

images/forms.py
from django import forms
from .models import Image, Comment

class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image', 'title')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, Http404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
from .forms import ImageCreateForm, CommentForm
from .models import Image, Comment
from common.decorators import ajax_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action, delete_action
from actions.models import Action
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from itertools import chain

@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST,
                                files=request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'Load new image', new_item)
            messages.success(request, 'Photo was added successfuly')
            return redirect(new_item.get_absolute_url())
        else:
            messages.error(request, 'Error adding your image')
    else:
        form = ImageCreateForm(instance=request.user)
    return render(request, 'images/image/create.html', {'form': form})

@login_required
def image_delete(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id, user=request.user)
            if action == 'delete':
                request.user.actions.get(target_id=image.id).delete()
                image.comments.all().delete()
                image.clear_thumbnails()
                image.image.delete()
                image.delete()
                #create_action(request.user, 'likes', image)
            else:
                pass
            return redirect('list')
        except:
            pass
    return redirect('images:list')

def image_detail(request, id):
        image = get_object_or_404(Image, id=id)
        comments = image.comments.filter(active=True)

        # if user not authenticated his name will be set to "Anonymous"
        # and he will not available to leave comment
        # если пользователь не вошел в систему его имя будет иметь значение "Anonymous"
        # и он не сможет оставлять комментарии
        if request.user.is_authenticated:
            if request.method == 'POST':
                # A comment was posted
                # комментарий был отправлен
                comment_form = CommentForm(data=request.POST)


                if comment_form.is_valid():
                    # Create Comment object but don't save to database yet
                    # Создать обьект комментария, но пока не сохранять в базу данных
                    new_comment = comment_form.save(commit=False)
                    # Assign the current post to the comment
                    # Привзать данный пост к комментарию
                    new_comment.image = image
                    new_comment.user = request.user
                    # Save the comment to the database
                    # сохранить в базу данных
                    new_comment.save()
            else:
                comment_form = CommentForm()

            #if user not already saw this image
            if request.user not in image.users_view.all():
                #increment total image views by 1
                image.users_view.add(request.user)
            return render(request, 'images/image/detail.html',
                                    {'image': image,
                                     'section': 'images',
                                     'your_name': request.user.profile.get_full_name,
                                     'comments': comments,
                                     'comment_form': comment_form})
        return render(request, 'images/image/detail.html',
                                {'image': image,
                                 'section': 'images',
                                 'your_name': 'Anonymous',
                                 'comments': comments})



@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    # if image_id and action exist
    # Если image_id и action существуют
    if image_id and action:
        # get image object where user push like
        # Взять обьект фотографии где пользователь поставил лайк
        image = Image.objects.get(id=image_id)
        # if action is valid
        # Если действие соответствует ожидаемому
        if action == 'like':
            # add to image object user like
            # Добавить к обьекту изображения лайк пользователя
            image.users_like.add(request.user)
            # Add action to database to view in news page
            # Добавить действие в базу данных для отображения в ленте новостей
            create_action(request.user, 'likes', image)
        # If action does not means like, it always mean dislike
        # Если action не соответствует ожидаемому, он в любом другом случае соответствует дизлайку
        else:
            # delete users like from image
            # Удалить пользовательский лайк из изображения
            image.users_like.remove(request.user)
            # delete action too
            # Удалить действие тоже
            request.user.actions.get(target_id=image.id).delete()
        return JsonResponse({'status':'ok'})
    return JsonResponse({'status':'ko'})

@login_required
def image_list(request):
    following_ids = request.user.following.values_list('id', flat=True)
    page = request.GET.get('page', 1)
    actions = ''

    # If user is following someone, filter only their actions
    # Если пользователь подписан на кого-нибудь, отфильтровать только их действия
    if following_ids:
        actions = Action.objects.filter(user_id__in=following_ids).select_related('user', 'user__profile').prefetch_related('target')
        # Filter only your actions
        # Отфильтровать только твои действия
        your_actions = Action.objects.filter(user=request.user)
        # combine two different lists of QuerySet
        # Соеденить два разных списка QuerySet
        actions = list(chain(actions, your_actions))
        # make list back to QuerySet, and order by created date
        # Вернуть список обратно в QuerySet, и отсортировать по дате создания
        actions = Action.objects.filter(pk__in=[x.pk for x in actions]).order_by('-created')

    paginator = Paginator(actions, 10)

    try:
        actions = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer return first page
        # Если страница не является числом, вернуть первую страницу
        actions = paginator.page(1)
    return render(request,
                  'images/image/list.html',
                   {'section': 'images', 'actions': actions, 'following_ids':following_ids})

images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}Upload an image{% endblock %}

{% block content %}
    <h1>Load your image</h1>
    <form action="." method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Save it!">
    </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
    <div class="detail-center">
        <h1>"{{ image.title }}"</h1>
        {% if image.user == request.user %}
            <span class='delete-btn' data-id="{{ image.id }}" data-action="delete">Delete image</span>
        {% endif %}
        {% thumbnail image.image "1280" as im %}
            <div class="image-full" style="background: url({{ im.url }}) no-repeat center center;background-size:contain;"></div>
        {% endthumbnail %}
        <!-- -->
        {% with total_likes=image.users_like.count users_like=image.users_like.all %}
            <div class="image-info">
                <div class='like-info'>
                    <span class='count'>{{ total_likes}}</span> like{{ total_likes|pluralize }}
                    <span class='like like_button' data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like">
                        {% if request.user not in users_like %}
                            Like
                        {% else %}
                        <span class='unlike' style='font-size: 8px;color: white;line-height: 26px;'>
                            Unlike
                        </span>

                        {% endif %}
                    </span>


                </div>
                <div class="image-info">
                    <span class='count-view'>{{ image.users_view.count }}</span>
                    view{{ image.users_view.count|pluralize }}
                </div>
                {{ image.description|linebreaks }}
            </div>

            <div class="image-likes">
                <div class="hidden_like" style="display: none;">
                    {% thumbnail user.profile.photo "150x150" as im %}
                        <div class='profile_link_in_likes' style="background: url({{ im.url }}) no-repeat center center; background-size:cover;"></div>
                    {% endthumbnail %}

                    <p>{{ your_name }}</p>
                </div>
                {% for user in image.users_like.all %}
                    <div class='profile_data'>
                        {% thumbnail user.profile.photo "150x150" as im %}
                            <div class='profile_link_in_likes' style="background: url({{ im.url }}) no-repeat center center; background-size:cover;"></div>
                        {% endthumbnail %}
                        <p>{{ user.profile.get_full_name }}</p>
                    </div>
                    {% empty %}
                {% endfor %}
            </div>
        {% endwith %}

        {% with comments.count as total_comments %}
            <h2>{{ total_comments }} coment{{ total_comments|pluralize }}</h2>
        {% endwith %}

        {% for comment in comments %}
            <div class="comment">
                <p class='info'>Comment by <a href="{{ comment.user.get_absolute_url }}">{{ comment.user.profile.get_full_name }}</a> {{ comment.created }}</p>
                {{ comment.body|linebreaks }}
            </div>
        {% empty %}
            <p>There are no comments yet.</p>
        {% endfor %}

        {% if user.is_authenticated %}
            {% if new_comment %}
                <h2>Your comment has been added.</h2>
            {% else %}
                <h2>Add a new comment</h2>
                <form action="." method="post">
                    {{ comment_form.as_p }}
                    {% csrf_token %}
                    <p><input type="submit" value="Add comment"></p>
                </form>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

{% block domready %}
    $('span.like').click(function(e){
        e.preventDefault();
        $.post('{% url "images:like" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data){

                if (data['status'] == 'ok')
                {
                    var previous_action = $('span.like').data('action');

                    // toggle data-action
                    $('span.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                    // toggle link text
                    $('span.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
                    if (previous_action == 'like') {
                        $('span.like').css('font-size', 8);
                    } else {
                        $('span.like').css('font-size', 9.3);
                    };

                    // update total likes
                    var previous_likes = parseInt($('.count').text());
                    $('.count').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);

                    // if selector .profile_data has selector p with your username, it will toggle
                    {% if user not in image.users_like.all %}
                        $(".hidden_like").toggle();
                    {% else %}
                        $(".profile_data:first:has(p:contains({{ your_name }}))").toggle();
                    {% endif %}
                }
            });

    });

    $('span.delete-btn').click(function(e){
        e.preventDefault();
        $.post('{% url "images:image_delete" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            });
    });
{% endblock %}

images/templates/images/image/list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}News{% endblock %}

{% block content %}
    <h1 style="text-align: center;">News</h1>
    <div class="infinite-container">
        {% if not actions %}
            <h2>Here will be show any actions</h2>
        {% else %}
            {% for action in actions %}
                {% with user=action.user profile=action.user.profile %}
                    <div class="action infinite-item">
                        <div class="images">
                            {% if profile.photo %}
                                {% thumbnail user.profile.photo "80x80" crop='100%' as im %}
                                    <a href="{{ user.get_absolute_url }}">
                                        <img src="{{ im.url }}" alt="{{ user.get_full_name }}" class="profile_photo">
                                    </a>
                                {% endthumbnail %}
                            {% endif %}

                            <a href="{{ user.get_absolute_url }}">{{ profile.get_full_name }}</a>
                            {{ action.verb }}

                            {% if action.target %}
                                {% with target=action.target %}
                                    {% if target.image %}
                                        {% thumbnail target.image "480" crop="100%" as im %}
                                            <a href="{{ target.get_absolute_url }}">
                                                <img src="{{ im.url }}" class="uploaded_photo">
                                            </a>
                                        {% endthumbnail %}
                                    {% endif %}
                                {% endwith %}
                            {% endif %}

                            {% if action.target %}
                                {% with target=action.target %}
                                    <a href="{{ target.get_absolute_url }}">{{ target.get_full_name }}</a>
                                    {% thumbnail target.profile.photo "80x80" crop='100%' as im %}
                                        <a href="{{ target.get_absolute_url }}">
                                            <img src="{{ im.url }}" alt="{{ target.profile.get_full_name }}" class="profile_photo">
                                        </a>
                                    {% endthumbnail %}
                                {% endwith %}
                            {% endif %}
                        </div>
                        <div class="info">
                            <p><span class='date'>{{ action.created|timesince }} ago</span></p>
                        </div>

                    </div>
                {% endwith %}
            {% endfor %}
        {% endif %}
    </div>

    {% if actions.has_next %}
        <a class='infinite-more-link' href="?page={{ actions.next_page_number }}">Next</a>
    {% endif %}
{% endblock %}

{% block domready %}
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0]
    });
{% endblock %}

images/templates/images/image/your_images_list.html
{% load thumbnail %}

{% for image in images reversed %}
    <a class='your_list__image' href="{{ image.get_absolute_url }}">
        {% thumbnail image.image "480" crop="100%" as im %}
            <div style="background: url({{ im.url }}) no-repeat center center;background-size:cover;"></div>
        {% endthumbnail %}
    </a>
{% endfor %}